### PR TITLE
Add unit tests for search_skill method

### PR DESCRIPTION
**Pull request by NeonDaniel**
Relies on #9 for neon store tests

### CODE REVIEW

**Comment by JarbasAl** [comment]
this is a good starter, should be easy to expand over time to improve coverage and test ither edge cases

will merge after #9 , thank you

**Comment by NeonDaniel** [comment]
Is this ready to merge?

**Comment by NeonDaniel** [comment]
Are there any changes to be made here, or is this ready to go?

**Comment by NeonDaniel** [comment]
Superseded by #27

**Pull request closed without merging**
